name: Deploy

on:
  push:
    branches:
      - main

  workflow_dispatch: # Allows you to run the workflow manually

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4

      - uses: pnpm/action-setup@v4
        with:
          version: 10

      - name: Install dependencies
        run: pnpm install

      - name: Build project
        run: pnpm run build

      - name: Upload production-ready build files
        uses: actions/upload-artifact@v4
        with:
          name: production-files
          path: ./dist

  deploy:
    name: Deploy
    needs: build
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/main'

    steps:
      - name: Download artifact
        uses: actions/download-artifact@v4
        with:
          name: production-files
          path: ./dist

      - name: Deploy to Render
        env:
          RENDER_SERVICE_ID: ${{ secrets.RENDER_SERVICE_ID }}
          RENDER_API_KEY: ${{ secrets.RENDER_API_KEY }}
        run: |
          curl -X POST "https://api.render.com/v1/services/$RENDER_SERVICE_ID/deploys" \
            -H "Accept: application/json" \
            -H "Authorization: Bearer $RENDER_API_KEY"

      - name: Notify Discord (Success)
        if: success()
        env:
          BOT_SERVER_URL: "https://03ff-14-177-243-93.ngrok-free.app/send"
        run: |
          curl -X POST "$BOT_SERVER_URL" \
               -H "Content-Type: application/json" \
               -d '{"status": "success", "message": "✅ Deployment successful!"}'

      - name: Notify Discord (Failure)
        if: failure()
        env:
          BOT_SERVER_URL: "https://03ff-14-177-243-93.ngrok-free.app/send"
        run: |
          curl -X POST "$BOT_SERVER_URL" \
               -H "Content-Type: application/json" \
               -d '{"status": "fail", "message": "❌ Deployment failed!"}'