name: CI/CD Notify Discord

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Run build
        run: echo "Building project..."

      - name: Notify Discord (Success)
        if: success()
        env:
          DISCORD_WEBHOOK_URL: ${{ secrets.DISCORD_WEBHOOK_URL }}
          THREAD_ID: ${{ secrets.DISCORD_THREAD_ID }}
        run: |
          curl -H "Content-Type: application/json" \
               -X POST \
               -d '{"username": "GitHub Actions", "content": "✅ Build Succeeded! 🎉"}' \
               "$DISCORD_WEBHOOK_URL?thread_id=$THREAD_ID"

      - name: Notify Discord (Failure)
        if: failure()
        env:
          DISCORD_WEBHOOK_URL: ${{ secrets.DISCORD_WEBHOOK_URL }}
          THREAD_ID: ${{ secrets.DISCORD_THREAD_ID }}
        run: |
          curl -H "Content-Type: application/json" \
               -X POST \
               -d '{"username": "GitHub Actions", "content": "❌ Build Failed! 😢"}' \
               "$DISCORD_WEBHOOK_URL?thread_id=$THREAD_ID"
